dockermetrics:
 image: daocloud.io/jamesxiong/dockermetrics
 ports:
  - "8686:8080"
 volumes:
  - /dev/log:/dev/log
  - /var/run/syslog:/var/run/syslog
  - /:/rootfs:ro
  - /var/run:/var/run:rw
  - /sys:/sys:ro
  - /var/lib/docker/:/var/lib/docker:ro
  - /var/run/docker.sock:/host/var/run/docker.sock
  - /dev:/host/dev
  - /proc:/host/proc:ro
  - /boot:/host/boot:ro
  - /lib/modules:/host/lib/modules:ro
  - /usr:/host/usr:rw
 environment:
   TZ: "Asia/Shanghai"
   log_level: "INFO"
   nats_host: "10.10.75.114"
   nats_port: "4222"
   nats_user: "nats"
   nats_password: "123kawd1adjashd"
   Influxdb_Host: "10.10.23.186:8086"
   Influxdb_Username: "sysdig"
   Influxdb_Password: "sysdig"
   Influxdb_Database: "sysdig"
   controllerport: "8080"
   SystemDomain: "daooffice.io"
   AppDomain: "daoapp.io"
 restart: always
 privileged: true
 container_name: "dockermetrics"

